### ISSUE TITLE
SplitClient in local mode permits invalid split names

### ISSUE THREAD

**Issue by swimmingdale** [splitio/java-client#114]
SplitClient permits using split names that are considered invalid in split.io SAAS.
Can be reproduced by adding split name 1.0.0-feature in the yml file like this:
`- 1.0.0-feature:
        treatment: "on"`
And then you can build the SplitClient:
`SplitClientConfig config = SplitClientConfig.builder()
                .splitFile("src/main/resources/split-file-config.yml").build();`
This will be successful.
While trying to create a split with that name in split.io UI will produce an error like this:
"Please rename your split. Split names must start with a letter and can contain "-_ a-z A-Z 0-9"

How It should be:
One shouldn't be able to create a SplitClient with invalid split names in local mode through yml file.
An exception should be thrown.

I hit this issue by first using the local mode then migrated to using the networked mode.

**Comment by chillaq** [comment]
Hi, I got an update from Engineering and there are many validations applied in Split UI that are not considered for localhost mode, because the localhost mode intended usage is only for unit tests, to test your code against all possible given treatments from Split. The YAML file is usually created and updated manually with split and treatments names based on existing Splits in UI.

I can submit a feature request to apply the same UI validation to localhost mode, could you please provide the business case and which company you are working in?

Thanks
Bilal

**Comment by chillaq** [comment]
Hi, I am closing out this ticket. If there is still an open issue or if we can be of further assistance on this topic, feel free to reachout to us, we will resume working on it.

Thanks
Bilal
