### ISSUE TITLE
Info message "Streaming service temporarily unavailable, working in polling mode" multiple times per hour

### ISSUE THREAD

**Issue by edwardsre** [splitio/java-client#363]
We have recently integrated the SplitClient for Java into our backend service and we regularly see the following info log statement 10 or more times per hour followed by a recovery after a few milliseconds (usually ~50 to 100 millis).

Since it is logged at info level, I'm wondering if this is expected/normal, or if there is some configuration we have missed that would help alleviate this other than changing the log level for SyncManager.

```
2022-12-19 16:48:32.234 INFO  13167 (SPLIT-PushStatusMonitor-0) [SyncManager]  Streaming service temporarily unavailable, working in polling mode.
2022-12-19 16:48:32.284 INFO  13167 (SPLIT-PushStatusMonitor-0) [SyncManager]  Streaming up and running.
```

We also occassionally see this output in the logs as well, but not as frequently.

```
2022-12-19 16:39:16.454 INFO  13119 (SPLIT-PushStatusMonitor-0) [SyncManager]  Retryable error in streaming subsystem. Switching to polling and retrying in 1000 seconds
```

This is the version we are using via maven

```xml
    <dependency>
      <groupId>io.split.client</groupId>
      <artifactId>java-client</artifactId>
      <version>4.6.0</version>
    </dependency>
```

**Comment by hbqdev** [comment]
Hi @edwardsre 
The Streaming functionality use websocket connection to split cloud, if the websocket connection is refused or blocked for any reason, the SDK will switch to polling mechanism. This is used to sync the SDK cache with any changes from Split cloud. Both ways will work though, so no impact on functionality.

So if you see the streaming messages it could be due to some transient networking blip that might have affected the streaming connections, then you will see this message and the SDK will switch to polling, then recover as you saw when the streaming is up again.

Thank you and Regards,

**Comment by edwardsre** [comment]
@hbqdev Is there a way to figure out the error being caused? I'm curious if it is something in our infrastructure, or if it is something with Splits servers. Seems like you would want to know what is causing this to determine if there is something that needs to change in the code.

**Comment by hbqdev** [comment]
Hi @edwardsre 
Can you please enable DEBUG logging and capture the logs that have the messages?

You can also send an email to support@split.io so that we can assist you better.

We also recommend monitoring your network see if there are any interruptions to the streaming connection.
Thank you and Regards,
Tin Tran

**Comment by hbqdev** [comment]
Hi @edwardsre 
Just checking in, do you still require assistant on this issue?

Thank you

**Comment by edwardsre** [comment]
@hbqdev Yes, I will try to get you the debug logs shortly.

**Comment by hbqdev** [comment]
Hi @edwardsre @christopher-nash 

The logs message you show are related to the long live SSE connections. The SSE connection is clsoed every hour or so
and the sdk fetches a new streaming token and reopens it, there should not be any interruptions as the SDK recovers really quickly from the timestamp that you saw.

If occasionally there is a  network blip that interrupts the SSE connection, then the SDK will also recover the same way with the same messages.

We hope that helps, let us know if you have further questions or concerns

Regards,

**Comment by edwardsre** [comment]
@hbqdev You indicated that the connection is closed every hour or so. Do you have any idea why we would be seeing this every 26 minutes on a regular basis?

**Comment by edwardsre** [comment]
> @hbqdev You indicated that the connection is closed every hour or so. Do you have any idea why we would be seeing this every 26 minutes on a regular basis?

It looks like this was across multiple hosts. On a single host, it updates about every 50 minutes as you stated.
