### ISSUE TITLE
Java SDK proxy endpoint support fails on unexpected headers

### ISSUE THREAD

**Issue by brendangibat** [splitio/java-client#70]
If the split synchronizer proxy is behind an ALB then AWS responds with some standard set cookie headers, which causes the client to fail on the expires attribute.
```split.org.apache.http.client.protocol.ResponseProcessCookies: Invalid cookie header: "Set-Cookie: AWSALB=<......>; Expires=Thu, 28 Feb 2019 17:47:59 GMT; Path=/". Invalid 'expires' attribute: Thu, 28 Feb 2019 17:47:59 GMT```

**Comment by goldensun8891** [comment]
Hi Brendan, 

Apologies that you're having these troubles! Our team will take a look and come back to you!

**Comment by SenhorCastor** [comment]
Hi Brendan, 

We are doing some research. We were able to reproduce the problem, but on our side it is only a warning:

```
Feb 25, 2019 3:05:18 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: AWSALB=<......>;Version=1;Comment=;Domain=localhost;Path=/;Max-Age=20;Expires=Mon, 25 Feb 2019 23:05:12 GMT". Invalid 'expires' attribute: Mon, 25 Feb 2019 23:05:12 GMT
```
Our Client does not fail. That points to [HttpClient library](https://github.com/apache/httpcomponents-client/blob/972f0158ec747ccb1dae0eb5e146ab59e49044b1/httpclient5/src/main/java/org/apache/hc/client5/http/protocol/ResponseProcessCookies.java#L122)

We are working on a fix for that (Setting CookiesSpec for our client for Standard), but we are wondering why on your side causes a failure and not a warning. Do you have the lines that are before and/or after that log line? 

Thanks!
PS: We are working on an RC version that we will share with you to see if it solves the problem

**Comment by brendangibat** [comment]
@SenhorCastor thanks for getting back so quickly! I'm going to close this issue since it looks to be invalid. After I reviewed what was happening - yes you are right it was only a warning, and there was an issue with configuration of the proxy. I was working in conjunction with the java split sdk and evaluating if I should use the proxy or wait for redis support. I had decided to wait on redis support for the java split sdk (or maybe if you guys accepted a PR?), so I put together both of these issues ( https://github.com/splitio/java-client/issues/69 ) as a collected update. 
Sorry about the invalid issue - and again, thank you for helping out!

**Comment by SenhorCastor** [comment]
Hey Brendan!

Glad you got to the bottom of this. We are still going to release 3.0.6 with that warning today.

Regarding support for Redis. It is a project we are going to prioritize and tackle it, we don't have a timeline yet.

Besides that, my understanding was that your team decided to start using the JAVA SDK in Proxy Mode since you were experiencing some delays or timeouts. Correct me if I am wrong, but you experienced those timeouts with version 3.0.3. On version 3.0.4 we made some improvements and also fixed a race condition that we are confident it addresses those timeouts. I would recommend giving it a try to the lates sdk version 3.0.5 (soon to be 3.0.6)

Again glad that you got to the bottom of this!
If you have any questions let us know
Fer
